[alembic]
# Path to the directory where Alembic stores its scripts.
script_location = alembic

# A placeholder URL which will be overridden by the runtime environment.
# This is usually set dynamically by env.py.
sqlalchemy.url = placeholder

# The 'file_template' and 'revision_template' options provide a way to
# customize the naming of new migration files. For example, to include a
# timestamp and a descriptive name in the filename.
# file_template = %%(rev)s_%%(slug)s
# revision_template = """# -*- coding: utf-8 -*-
# import datetime

# from alembic import op
# import sqlalchemy as sa

# %%(up_revision)s
# """

# To auto-generate migrations, specify the target metadata here.
# For example:
# target_metadata = myapp.models.Base.metadata

# Set to 'true' to include comment documentation from models in the migration.
# comment_token_in_migration = False

# The 'timezone' option sets the timezone for the timestamp in migration files.
# Default is None, which means the local timezone.
# timezone = UTC

[loggers]
keys = root,alembic

[handler_root]
class = StreamHandler
formatter = generic
args = (sys.stderr,)

[logger_root]
level = WARNING
handlers = root
qualname =

[logger_alembic]
level = INFO
handlers = root
qualname = alembic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
